/*States*/
#define STATE_NOTIMESET 0
#define STATE_TIMESET 1
#define STATE_SETSETTINGMODE 50
#define STATE_TIMESETMIN 51
#define STATE_TIMESETHR 52
#define STATE_TIMESETDAY 53
#define STATE_TIMESETMONTH 54
#define STATE_TIMESETYEAR 55
#define STATE_ALARMSETMIN 60
#define STATE_ALARMSETHR 61
#define STATE_SETBRIGHTNESS 80