/*States*/
#define STATE_NOTIMESET 0
#define STATE_TIMESET 1
#define STATE_SETSETTINGMODE 50
#define STATE_TIMESETMIN 51
#define STATE_TIMESETHR 52
#define STATE_TIMESETDAY 53
#define STATE_TIMESETMONTH 54
#define STATE_TIMESETYEAR 55
#define STATE_ALARMSETMIN 60
#define STATE_ALARMSETHR 61
#define STATE_SETBRIGHTNESS 80

/*SettingMenu*/
#define SETTING_CHAPTER_TIME 0
#define SETTING_CHAPTER_ALARMTIME 1
#define SETTING_CHAPTER_DISPLAYBRIGHTNESS 3
#define SETTING_CHAPTER_REFRESHRATE 4
#define SETTING_CHAPTER_EXIT 2

